name: flutter_ydl
description: "GUI per ydl"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  platform_detector: ^0.2.0
  window_manager: ^0.5.1
  block_ui: ^0.0.5
  flutter_spinkit: ^5.2.2
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
